services:
  caddy:
      image: caddy:2
      environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      container_name: caddy
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"  # Для HTTP/3
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - api
        - frontend
      networks:
        - app-network
      extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    env_file:
      - ../cmdnt-website/.env
    build:
      context: .
      dockerfile: backend/API/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: Server=db;Port=3306;Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD}
      JWT__Key: ${JWT_KEY:-super-secret-key}
      ADMIN_SEED_EMAIL: ${ADMIN_SEED_EMAIL:-admin}
      ADMIN_SEED_PASSWORD: ${ADMIN_SEED_PASSWORD:-admin}
      ASPNETCORE_URLS: http://+:8080
      APPLY_MIGRATIONS_ON_STARTUP: "true"
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - api
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:
  db_data:
    name: ${DB_VOLUME_NAME}

networks:
  app-network:
    driver: bridge