// <auto-generated />
using System;
using Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("Core.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("Core.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Core.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Course")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Group", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = 4,
                            Name = "ИСПВ-21"
                        },
                        new
                        {
                            Id = 2,
                            Course = 4,
                            Name = "ИСПВ-22"
                        },
                        new
                        {
                            Id = 3,
                            Course = 3,
                            Name = "ИСПВ-32"
                        },
                        new
                        {
                            Id = 4,
                            Course = 2,
                            Name = "ИСПВ-42"
                        },
                        new
                        {
                            Id = 5,
                            Course = 1,
                            Name = "ИСПВ-52"
                        },
                        new
                        {
                            Id = 6,
                            Course = 4,
                            Name = "ИСПП-21"
                        },
                        new
                        {
                            Id = 7,
                            Course = 3,
                            Name = "ИСПП-31"
                        },
                        new
                        {
                            Id = 8,
                            Course = 3,
                            Name = "ИСПП-34"
                        },
                        new
                        {
                            Id = 9,
                            Course = 3,
                            Name = "ИСПП-35"
                        },
                        new
                        {
                            Id = 10,
                            Course = 2,
                            Name = "ИСПП-41"
                        },
                        new
                        {
                            Id = 11,
                            Course = 2,
                            Name = "ИСПП-43"
                        },
                        new
                        {
                            Id = 12,
                            Course = 2,
                            Name = "ИСПП-45"
                        },
                        new
                        {
                            Id = 13,
                            Course = 1,
                            Name = "ИСПП-51"
                        },
                        new
                        {
                            Id = 14,
                            Course = 1,
                            Name = "ИСПП-55"
                        },
                        new
                        {
                            Id = 15,
                            Course = 5,
                            Name = "ИСС-11"
                        },
                        new
                        {
                            Id = 16,
                            Course = 5,
                            Name = "ИСС-12"
                        },
                        new
                        {
                            Id = 17,
                            Course = 4,
                            Name = "ИСС-21"
                        },
                        new
                        {
                            Id = 18,
                            Course = 4,
                            Name = "ИСС-22"
                        },
                        new
                        {
                            Id = 19,
                            Course = 4,
                            Name = "ИСС-25"
                        },
                        new
                        {
                            Id = 20,
                            Course = 3,
                            Name = "ИСС-31"
                        },
                        new
                        {
                            Id = 21,
                            Course = 3,
                            Name = "ИСС-32"
                        },
                        new
                        {
                            Id = 22,
                            Course = 3,
                            Name = "ИСС-35"
                        },
                        new
                        {
                            Id = 23,
                            Course = 2,
                            Name = "ИСС-41"
                        },
                        new
                        {
                            Id = 24,
                            Course = 2,
                            Name = "ИСС-45"
                        },
                        new
                        {
                            Id = 25,
                            Course = 1,
                            Name = "ИСС-51"
                        },
                        new
                        {
                            Id = 26,
                            Course = 1,
                            Name = "ИСС-52"
                        },
                        new
                        {
                            Id = 27,
                            Course = 4,
                            Name = "КСК-21"
                        },
                        new
                        {
                            Id = 28,
                            Course = 4,
                            Name = "КСК-22"
                        },
                        new
                        {
                            Id = 29,
                            Course = 3,
                            Name = "КСК-31"
                        },
                        new
                        {
                            Id = 30,
                            Course = 2,
                            Name = "КСК-41"
                        },
                        new
                        {
                            Id = 31,
                            Course = 1,
                            Name = "КСК-51"
                        },
                        new
                        {
                            Id = 32,
                            Course = 4,
                            Name = "ОИБ-21"
                        },
                        new
                        {
                            Id = 33,
                            Course = 3,
                            Name = "ОИБ-31"
                        },
                        new
                        {
                            Id = 34,
                            Course = 3,
                            Name = "ОИБ-35"
                        },
                        new
                        {
                            Id = 35,
                            Course = 2,
                            Name = "ОИБ-41"
                        },
                        new
                        {
                            Id = 36,
                            Course = 1,
                            Name = "ОИБ-51"
                        },
                        new
                        {
                            Id = 37,
                            Course = 2,
                            Name = "П-41"
                        },
                        new
                        {
                            Id = 38,
                            Course = 4,
                            Name = "Р-21"
                        },
                        new
                        {
                            Id = 39,
                            Course = 3,
                            Name = "РМТ-31"
                        },
                        new
                        {
                            Id = 40,
                            Course = 3,
                            Name = "РМТ-35"
                        },
                        new
                        {
                            Id = 41,
                            Course = 2,
                            Name = "РМТ-41"
                        },
                        new
                        {
                            Id = 42,
                            Course = 2,
                            Name = "РМТ-45"
                        },
                        new
                        {
                            Id = 43,
                            Course = 1,
                            Name = "РМТ-51"
                        },
                        new
                        {
                            Id = 44,
                            Course = 1,
                            Name = "РМТ-52"
                        },
                        new
                        {
                            Id = 45,
                            Course = 4,
                            Name = "ССА-21"
                        },
                        new
                        {
                            Id = 46,
                            Course = 4,
                            Name = "ССА-22"
                        },
                        new
                        {
                            Id = 47,
                            Course = 3,
                            Name = "ССА-31"
                        },
                        new
                        {
                            Id = 48,
                            Course = 3,
                            Name = "ССА-35"
                        },
                        new
                        {
                            Id = 49,
                            Course = 2,
                            Name = "ССА-41"
                        },
                        new
                        {
                            Id = 50,
                            Course = 1,
                            Name = "ССА-51"
                        },
                        new
                        {
                            Id = 51,
                            Course = 1,
                            Name = "ССА-55"
                        });
                });

            modelBuilder.Entity("Core.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("Core.Models.Resettlement", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckInDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("StudentId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("Resettlement", (string)null);
                });

            modelBuilder.Entity("Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasDefaultValue("Воспитатель");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Комендант"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Воспитатель"
                        });
                });

            modelBuilder.Entity("Core.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int")
                        .HasColumnName("Room");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("Core.Models.RoomEquipment", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("RoomId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RoomEquipment", (string)null);
                });

            modelBuilder.Entity("Core.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<bool>("IsHeadman")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Origin")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Core.Models.Contact", b =>
                {
                    b.HasOne("Core.Models.Student", "Student")
                        .WithMany("Contacts")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Models.Note", b =>
                {
                    b.HasOne("Core.Models.Student", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Note_Student");

                    b.HasOne("Core.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Note_User");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Models.Resettlement", b =>
                {
                    b.HasOne("Core.Models.Room", "Room")
                        .WithMany("Resettlements")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Resettlement_Room");

                    b.HasOne("Core.Models.Student", "Student")
                        .WithMany("Resettlements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Resettlement_Student");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Core.Models.Room", b =>
                {
                    b.HasOne("Core.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Room_Building");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Core.Models.RoomEquipment", b =>
                {
                    b.HasOne("Core.Models.Equipment", "Equipment")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomEquipment_Equipment");

                    b.HasOne("Core.Models.Room", "Room")
                        .WithMany("RoomEquipments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomEquipment_Room");

                    b.Navigation("Equipment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Core.Models.Student", b =>
                {
                    b.HasOne("Core.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Student_Group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.HasOne("Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Core.Models.Equipment", b =>
                {
                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("Core.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Core.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Models.Room", b =>
                {
                    b.Navigation("Resettlements");

                    b.Navigation("RoomEquipments");
                });

            modelBuilder.Entity("Core.Models.Student", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Notes");

                    b.Navigation("Resettlements");
                });

            modelBuilder.Entity("Core.Models.User", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
